### ISSUE TITLE
Investigation: Credential, PEX and Checker

### ISSUE THREAD

**Issue by jdsika** [GAIA-X4PLC-AAD/ssi-to-oidc-bridge#13]
# Context
We want to deploy the bridge to let people from GaiaX easily test it.

# Credential requirement
The long-term goal is to support "member" (company) and "user" (employee) credentials from [DEMIM](https://github.com/ASCS-eV/credentials).

Staging:
https://staging.identity.ascs.digital
Main:
https://identity.ascs.digital

* We need to verify and compare the GaiaX credential and the DEMIM credentials. (GAIA X DIGITAL CLEARING HOUSE)
* Are the GaiaX credentials final?

# Minimim credential
The minimum should be the email credential AND the blockchain DID credential. Both can be easiy generated by [talao.co](https://talao.co/). 

* Create a PEX for a combination those two credentials
* Research how to check credential attributes
* Check attribute combination 
* How to put the PEX into a registry? (Trsut Framework)
* Smart contract Status List 2021 @srajitsakhuja

# Goal:
Create different tickets out of this research ticket

**Comment by jfelixh** [comment]
Mostly project specific things and thus not discussed in this repo. Some new cards over here: https://github.com/GAIA-X4PLC-AAD/gx-credentials/issues
